<?php
get_template_part('widgets/flickr-widget');
get_template_part('widgets/tweets-widget');
get_template_part('widgets/socialicons-widget');
get_template_part('widgets/featured-property-posts');
get_template_part('widgets/location-widget');
get_template_part('widgets/property-types');
get_template_part('widgets/properties-by-status');
?>